const vulnerabilities = [
    {
        secret_name: "AWS Access Key",
        description: "A potential secret was detected in the source code. This may expose sensitive credentials.",
        severity_level: "High",
        first_detected: "2025-08-18T12:34:56Z",
        secret_type: "Key",
        affected_file_path: "config/aws_keys.py",
        line_number: 42,
        code_snippet: "aws_access_key_id = \"AKIA***\"",
        commit_hash: "a1b2c3d4",
        author: "John Doe",
        timestamp: "2025-08-18T12:01:00Z",
        platform: "hts-secretscanner",
        cwe: "CWE-798: Use of Hard-coded Credentials",
        remediation: "Remove hardcoded secrets and use a secure secret manager."
    },
    {
        secret_name: "Google API Key",
        description: "A Google API key was found, which may allow unauthorized access to Google services.",
        severity_level: "High",
        first_detected: "2025-08-19T09:45:12Z",
        secret_type: "API Key",
        affected_file_path: "src/config/google.js",
        line_number: 18,
        code_snippet: "const gkey = \"AIza***\"",
        commit_hash: "d4e5f6g7",
        author: "Alice Smith",
        timestamp: "2025-08-19T09:30:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Use environment variables or a secrets manager."
    },
    {
        secret_name: "Stripe Secret Key",
        description: "Stripe secret key detected. This could allow attackers to manipulate payment processes.",
        severity_level: "Critical",
        first_detected: "2025-08-20T14:15:33Z",
        secret_type: "API Key",
        affected_file_path: "backend/payments/stripe.js",
        line_number: 55,
        code_snippet: "sk_test_51L***",
        commit_hash: "h8i9j0k1",
        author: "Rajesh Kumar",
        timestamp: "2025-08-20T14:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Rotate Stripe keys and store them securely."
    },
    {
        secret_name: "Slack Bot Token",
        description: "Slack bot token detected, which may allow attackers to control bot actions.",
        severity_level: "High",
        first_detected: "2025-08-21T11:23:45Z",
        secret_type: "Token",
        affected_file_path: "slack/integration.env",
        line_number: 6,
        code_snippet: "SLACK_BOT_TOKEN=xoxb-123***",
        commit_hash: "l2m3n4o5",
        author: "Sarah Lee",
        timestamp: "2025-08-21T11:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Revoke exposed token and rotate credentials."
    },
    {
        secret_name: "GitHub Personal Access Token",
        description: "A GitHub personal access token was committed, which may expose repository permissions.",
        severity_level: "Critical",
        first_detected: "2025-08-22T08:56:22Z",
        secret_type: "Token",
        affected_file_path: ".github/workflows/deploy.yml",
        line_number: 72,
        code_snippet: "GITHUB_TOKEN=ghp_abcd1234***",
        commit_hash: "p6q7r8s9",
        author: "Michael Brown",
        timestamp: "2025-08-22T08:30:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Remove the token and generate a new one."
    },
    {
        secret_name: "Twilio Auth Token",
        description: "Twilio authentication token detected, which may allow sending SMS on behalf of the account.",
        severity_level: "High",
        first_detected: "2025-08-23T07:12:00Z",
        secret_type: "Token",
        affected_file_path: "services/twilio.js",
        line_number: 29,
        code_snippet: "authToken: \"abcd1234***\"",
        commit_hash: "t0u1v2w3",
        author: "Emma Wilson",
        timestamp: "2025-08-23T07:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Use environment variables for sensitive data."
    },
    {
        secret_name: "Azure Storage Key",
        description: "Azure storage account key detected. Attackers could gain full access to storage resources.",
        severity_level: "Critical",
        first_detected: "2025-08-23T18:10:10Z",
        secret_type: "Key",
        affected_file_path: "cloud/azure/storage.json",
        line_number: 11,
        code_snippet: "\"accountKey\": \"abcdEfgh***\"",
        commit_hash: "x4y5z6a7",
        author: "Daniel Chen",
        timestamp: "2025-08-23T18:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Rotate the key and configure via Azure Key Vault."
    },
    {
        secret_name: "Postgres Password",
        description: "Hardcoded Postgres database password detected.",
        severity_level: "High",
        first_detected: "2025-08-24T09:22:30Z",
        secret_type: "Password",
        affected_file_path: "db/config.js",
        line_number: 20,
        code_snippet: "password: \"mypassword123\"",
        commit_hash: "b8c9d0e1",
        author: "Sophia White",
        timestamp: "2025-08-24T09:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-259: Use of Hard-coded Password",
        remediation: "Remove hardcoded DB passwords and use env variables."
    },
    {
        secret_name: "JWT Secret",
        description: "JWT secret key found in the code. Attackers can forge authentication tokens.",
        severity_level: "Critical",
        first_detected: "2025-08-24T10:11:45Z",
        secret_type: "Secret",
        affected_file_path: "auth/jwt.js",
        line_number: 9,
        code_snippet: "const JWT_SECRET = \"supersecret123\"",
        commit_hash: "f2g3h4i5",
        author: "Lucas Miller",
        timestamp: "2025-08-24T10:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Store secrets in secure vaults."
    },
    {
        secret_name: "SendGrid API Key",
        description: "SendGrid API key detected. Attackers could send spam emails via account.",
        severity_level: "High",
        first_detected: "2025-08-25T07:40:15Z",
        secret_type: "API Key",
        affected_file_path: "mailer/sendgrid.env",
        line_number: 3,
        code_snippet: "SENDGRID_KEY=SG.abcd1234***",
        commit_hash: "j6k7l8m9",
        author: "Olivia Johnson",
        timestamp: "2025-08-25T07:30:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Revoke API key and use encrypted storage."
    },
    {
        secret_name: "SSH Private Key",
        description: "Private SSH key detected. This could allow unauthorized server access.",
        severity_level: "Critical",
        first_detected: "2025-08-25T13:12:00Z",
        secret_type: "Key",
        affected_file_path: "keys/id_rsa",
        line_number: 1,
        code_snippet: "-----BEGIN PRIVATE KEY-----",
        commit_hash: "n0o1p2q3",
        author: "David Martinez",
        timestamp: "2025-08-25T13:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-321: Use of Hard-coded Cryptographic Key",
        remediation: "Delete exposed key and generate a new pair."
    },
    {
        secret_name: "PayPal Client Secret",
        description: "PayPal client secret detected in codebase.",
        severity_level: "High",
        first_detected: "2025-08-26T08:55:00Z",
        secret_type: "Secret",
        affected_file_path: "payments/paypal.json",
        line_number: 15,
        code_snippet: "\"client_secret\": \"abc123***\"",
        commit_hash: "r4s5t6u7",
        author: "Ethan Clark",
        timestamp: "2025-08-26T08:30:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Use PayPal SDK secure authentication."
    },
    {
        secret_name: "Facebook App Secret",
        description: "Facebook app secret detected. Attackers could impersonate app requests.",
        severity_level: "High",
        first_detected: "2025-08-26T12:12:30Z",
        secret_type: "Secret",
        affected_file_path: "social/facebook.env",
        line_number: 4,
        code_snippet: "FB_APP_SECRET=abcd123***",
        commit_hash: "v8w9x0y1",
        author: "Grace Kim",
        timestamp: "2025-08-26T12:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Rotate secret and avoid storing in repo."
    },
    {
        secret_name: "MongoDB Connection String",
        description: "MongoDB connection string with embedded password detected.",
        severity_level: "High",
        first_detected: "2025-08-27T09:00:45Z",
        secret_type: "Connection String",
        affected_file_path: "server/db.js",
        line_number: 33,
        code_snippet: "mongodb://admin:password123@localhost:27017/db",
        commit_hash: "z2a3b4c5",
        author: "Henry Adams",
        timestamp: "2025-08-27T08:45:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-259",
        remediation: "Remove hardcoded credentials from URI."
    },
    {
        secret_name: "DigitalOcean Token",
        description: "DigitalOcean API token found. Attackers could control cloud resources.",
        severity_level: "Critical",
        first_detected: "2025-08-27T14:20:15Z",
        secret_type: "Token",
        affected_file_path: "infra/do_token.env",
        line_number: 2,
        code_snippet: "DO_TOKEN=abc123***",
        commit_hash: "d6e7f8g9",
        author: "Isabella Moore",
        timestamp: "2025-08-27T14:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Rotate DigitalOcean token and store in vault."
    },
    {
        secret_name: "Heroku API Key",
        description: "Heroku API key exposed in repository.",
        severity_level: "High",
        first_detected: "2025-08-28T10:05:22Z",
        secret_type: "API Key",
        affected_file_path: "deploy/heroku.env",
        line_number: 5,
        code_snippet: "HEROKU_KEY=abcd123***",
        commit_hash: "h1i2j3k4",
        author: "Jack Nguyen",
        timestamp: "2025-08-28T10:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Revoke key from Heroku dashboard."
    },
    {
        secret_name: "SMTP Credentials",
        description: "SMTP username and password exposed in source code.",
        severity_level: "High",
        first_detected: "2025-08-28T15:40:10Z",
        secret_type: "Password",
        affected_file_path: "mailer/smtp.conf",
        line_number: 12,
        code_snippet: "username=admin password=12345",
        commit_hash: "l5m6n7o8",
        author: "Karen Scott",
        timestamp: "2025-08-28T15:30:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-259",
        remediation: "Remove hardcoded credentials."
    },
    {
        secret_name: "Okta API Token",
        description: "Okta API token detected in environment file.",
        severity_level: "Critical",
        first_detected: "2025-08-29T09:22:00Z",
        secret_type: "Token",
        affected_file_path: "auth/okta.env",
        line_number: 3,
        code_snippet: "OKTA_TOKEN=00abc123***",
        commit_hash: "p9q0r1s2",
        author: "Leo Thomas",
        timestamp: "2025-08-29T09:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Rotate Okta tokens immediately."
    },
    {
        secret_name: "Dropbox API Key",
        description: "Dropbox API key exposed in repo.",
        severity_level: "High",
        first_detected: "2025-08-29T18:11:45Z",
        secret_type: "API Key",
        affected_file_path: "integrations/dropbox.js",
        line_number: 22,
        code_snippet: "DROPBOX_KEY=sl.Abc123***",
        commit_hash: "t3u4v5w6",
        author: "Maria Perez",
        timestamp: "2025-08-29T18:00:00Z",
        platform: "kics-gitleaks",
        cwe: "CWE-798",
        remediation: "Rotate key and use encrypted configs."
    }
];

export default vulnerabilities;