import React, { useEffect, useState } from "react";

export function KicsScan() {
    const [vulnerabilityData, setvulnerabilityData] = useState();
    const severityColors = {
        High: "bg-red-500 text-white",
        Medium: "bg-yellow-400 text-black",
        Low: "bg-green-500 text-white",
    };
    useEffect(()=> {
        const vulnerability = {
            secret_name: "AWS Access Key",
            description: "A potential secret was detected in the source code. This may expose sensitive credentials.",
            severity_level: "High",
            first_detected: "2025-08-18T12:34:56Z",
            secret_type: "Key",
            affected_file_path: "config/aws_keys.py",
            line_number: 42,
            code_snippet: "aws_access_key_id = \"AKIA***\"",
            commit_hash: "a1b2c3d4",
            author: "John Doe",
            timestamp: "2025-08-18T12:01:00Z",
            platform: "hts-secretscanner",
            cwe: "CWE-798: Use of Hard-coded Credentials",
            remediation: "Remove hardcoded secrets and use a secure secret manager."
        };
        setvulnerabilityData(vulnerability);
    },[])
    if (!vulnerabilityData) return <div className="text-center p-6">Loading...</div>;
    return (
        <div className="max-w-3xl mx-auto my-10 shadow-sm rounded-xl" style={{backgroundColor: "#fafafa"}}>
            {/* Header */}
            <div className="px-6 py-4 border-b border-gray-200 text-center">
                <h1 className="text-2xl font-semibold text-gray-800">
                Vulnerability Report
                </h1>
                <p className="text-sm text-gray-500 mt-1">
                Generated by {vulnerabilityData.platform}
                </p>
            </div>

            {/* Content */}
            <div className="px-6 py-6 space-y-6">
                <section>
                    <h3 className="text-lg font-medium text-gray-700 mb-2">
                        General Information
                    </h3>
                    <div className="grid grid-cols-2 gap-4 text-sm">
                        <div className="flex items-center gap-3 text-sm">
                            <p className="text-gray-500 font-medium">Secret Name:</p>
                            <p className="font-semibold text-gray-800">
                                {vulnerabilityData.secret_name}
                            </p>
                        </div>
                        <div className="flex items-center gap-3 text-sm">
                            <span className="text-gray-500 font-medium">Severity Level:</span>
                            <span className={`px-3 pb-1 rounded-full font-semibold ${ severityColors[vulnerabilityData.severity_level] || "bg-gray-300 text-gray-700" }`}>
                                {vulnerabilityData.severity_level}
                            </span>
                        </div>
                        <div className="flex items-center gap-3 text-sm">
                            <p className="text-gray-500 font-medium">First Detected:</p>
                            <p className="font-semibold text-gray-800">
                                {new Date(vulnerabilityData.first_detected).toLocaleString()}
                            </p>
                        </div>
                        <div className="flex items-center gap-3 text-sm">
                            <p className="text-gray-500 font-medium">Secret Type:</p>
                            <p className="font-semibold text-gray-800">
                                {vulnerabilityData.secret_type}
                            </p>
                        </div>
                    </div>
                </section>
                <section>
                    <h3 className="text-lg font-medium text-gray-700 mb-2">
                        Source Details
                    </h3>
                    <div className="text-sm space-y-2">
                        <p>
                            <span className="text-gray-500">Affected File:</span>{" "}
                            <span className="font-medium text-gray-800">
                                {vulnerabilityData.affected_file_path}
                            </span>
                        </p>
                        <p>
                            <span className="text-gray-500">Line Number:</span>{" "}
                            <span className="font-medium text-gray-800">
                                {vulnerabilityData.line_number}
                            </span>
                        </p>
                        <p><span className="text-gray-500">Code Snippet:</span></p>
                        <pre className="bg-gray-100 p-3 rounded-md text-sm text-gray-700 overflow-x-auto">
                            {vulnerabilityData.code_snippet}
                        </pre>
                        <p>
                            <span className="text-gray-500">Commit Hash:</span>{" "}
                            <span className="font-mono text-gray-800">
                                {vulnerabilityData.commit_hash}
                            </span>
                        </p>
                        <p>
                            <span className="text-gray-500">Author:</span>{" "}
                            <span className="font-medium text-gray-800">
                                {vulnerabilityData.author}
                            </span>
                        </p>
                        <p>
                            <span className="text-gray-500">Commit Timestamp:</span>{" "}
                            <span className="font-medium text-gray-800">
                                {new Date(vulnerabilityData.timestamp).toLocaleString()}
                            </span>
                        </p>
                    </div>
                </section>
                <section>
                    <h3 className="text-lg font-medium text-gray-700 mb-2">
                        Security Reference
                    </h3>
                    <p className="text-sm text-gray-700">
                        <span className="text-gray-500">CWE:</span>{" "}
                        {vulnerabilityData.cwe}
                    </p>
                </section>
                <section>
                    <h3 className="text-lg font-medium text-gray-700 mb-2">
                        Remediation
                    </h3>
                    <p className="text-sm text-gray-700">
                        {vulnerabilityData.remediation}
                    </p>
                </section>
            </div>
        </div>
    );
}